server:
  port: ${FINREM_DOCUMENT_GENERATOR_PORT:4009}

service:
  pdf-service:
    uri: ${PDF_SERVICE_BASEURL:https://docmosis-development.platform.hmcts.net/rs/render}
    accessKey: ${PDF_SERVICE_ACCESS_KEY:}
    health:
      uri: ${PDF_SERVICE_HEALTH_URL:https://docmosis-development.platform.hmcts.net/rs/status}
  evidence-management-client-api:
    uri: ${EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL:http://localhost:4006}/emclientapi/version/1/upload
    delete-uri: ${EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL:http://localhost:4006}/emclientapi/version/1/deleteFile
    health:
      context-path: ${EVIDENCE_MANAGEMENT_CLIENT_API_HEALTH_ENDPOINT:/health}
      uri: ${EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL:http://localhost:4006}${service.evidence-management-client-api.health.context-path}

http:
  connect:
    timeout: 30000
    request:
      timeout: 30000
    read:
      timeout: 30000

info:
  app:
    name: ${spring.application.name}

evidence-management-api:
  service:
    stub:
      enabled: false

documentation:
  swagger:
    enabled: ${SWAGGER_ENABLED:true}

spring:
  application:
    name: "finrem-dgcs"
  resources:
    static-locations:

document:
  pdf:
    familyCourtImgKey: "familycourt"
    familyCourtImgVal: "[userImage:familycourt.png]"
    hmctsImgKey: "hmcts"
    hmctsImgVal: "[userImage:hmcts.png]"
    displayTemplateKey: "displayTemplateOnly"
    displayTemplateVal: "1"

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
# HEALTH ENDPOINT CONFIG
# Enable the health endpoint
# Enable sensitive health information
# Defines the URL of the health check to ${management.context-path}/health
# Caching period in milliseconds of health endpoint
# METRICS ENDPOINT CONFIG
# Enable the metrics endpoint
# Enable sensitive metrics information
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      cache:
        time-to-live: 5000
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: info, health, metrics

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.finrem.documentgenerator: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
